#!/bin/sh
#########################################################################
#
# $Author: bucknerk $
# $Id: print_get,v 1.2 2008/04/16 13:48:23 bucknerk Exp $
#
# $Log: print_get,v $
# Revision 1.2  2008/04/16 13:48:23  bucknerk
# revised
#
# Revision 1.1  2008/04/08 14:42:05  bucknerk
# new
#
# Revision 1.1  2008/03/31 15:38:05  bucknerk
# new
#
#
#################################################################
# taken from cina_eval
#
# Revision 1.5  2007/12/05 19:52:20  bucknerk
# deleted portal
#
# Revision 1.4  2007/11/09 16:25:35  bucknerk
# added portal
#
# Revision 1.3  2007/10/17 14:48:22  bucknerk
# Added a call to create_index
#
# Revision 1.2  2007/09/19 12:45:48  bucknerk
# reaction_handlers.inc
#
# Revision 1.1.1.1  2007/09/06 13:34:19  bucknerk
# Database documentation
#
#
#
# 
# This is a simple script that queries the mysql databases, gets the table
# information and then uses the 'format_it.awk' script to format the results
# into html files.  the last little bit changes the date in the 'index.html'
# file. The only files that should be placed into CVS are this file, the awk
# script, the index.html file and 'masses.png' which is the graphic.
#########################################################################
dbnames="mass_model cinad reaction_test"
if [ -e "db_index.txt" ]; then
  if unlink "db_index.txt"; then echo -e "removed db_index.txt\n";fi
fi

for t in $dbnames
do
  if [ -e $t'_desc.txt' ]; then
    echo "file exists: $t'_desc.txt'"
    if unlink $t'_desc.txt'; then echo -e "removed file\n"; fi
  fi

  tables=`mysqlshow $t | sed -e 's/[-|+]//g' -e 's/Database: '$t'//' -e 's/Tables //' | tr -s ' '`
  echo $tables

  for i in $tables
    do
      name=`echo $i | sed 's/_/\\_/g'`
      echo -e "######\n\n" >> $t'_desc.txt'
      #echo $name
      mysqlshow $t "$name" '%' >> $t'_desc.txt'
    done

  echo -e "######\n\n" >> $t'_desc.txt'

  ./print_format.awk $t'_desc.txt' 
done
# clean up a little.

/bin/rm -f *_desc.txt


# this is the enscript command I am currently using ot print to printer
# cp6025_duplex.
enscript -P cp6025_duplex -f Courier9 -2rh -b '%W|DataBase Info Index' -F Times-Italic14 --margins=::18:36 -L 48 db_index.txt

for i in `ls db_*_tables.txt`
do
  dbname=`echo $i | sed -e 's/^db_//' -e 's/_tables.txt//'`
  enscript -P cp6025_duplex -f Courier9 -2rh -b '%W|DataBase '$dbname'|Page $% of $=' -F Times-Italic14 --margins=::10:36 -L 48 $i
done
  
# I haven't been able to make the printer do 
# top-to-bottom printing but at least it is duplex.  The script that formats
# the output used to insert ctrl-L at the beginning of each table. But now that
# is not needed 

